# This is simply for use in development
# We will run docker build -f Dockerfile.dev . to use this docker file
# Specify a base image
FROM node:alpine

WORKDIR /app

COPY package.json .

RUN npm install 

COPY . .

CMD ["npm", "run", "start"]